version: "3.9"

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./server/.env 

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5173:5173"       # <— đây là phần bạn hỏi: đổi cổng 8080 để tránh trùng
    depends_on:
      - backend
    restart: always
