version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    restart: always
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"          # Production mode
      # - "5173:5173"      # Dev mode
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
