version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"     # port host:container
    restart: always
    env_file:
      - ./server/.env 

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:80"       # nếu build production (nginx)
      # hoặc "5173:5173" nếu chạy dev server (vite)
    depends_on:
      - backend
    restart: always
