version: "3.9"

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./server/.env   # <— thêm dòng này để load biến môi trường như MONGO_URI

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "8080:80"       # <— đây là phần bạn hỏi: đổi cổng 8080 để tránh trùng
    depends_on:
      - backend
    restart: always
